services:
  rustapp: 
    container_name: rustapp
    image: jainam-r:latest
    build:
      context: ./backend
      dockerfile: rust.dockerfile
      args:
        DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes: 
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}